apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-backend
spec:
  replicas: 2
  selector:
    matchLabels: {app: backend}
  template:
    metadata:
      labels: {app: backend}
    spec:
      containers:
      - name: backend
        image: sanasini/quiz-backend:latest
        ports: [{containerPort: 3000}]
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/quizdb"
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-backend
spec:
  selector: {app: backend}
  ports: [{port: 3000, targetPort: 3000}] 